# properties 配置
person:
  name: Double
  age:  24
  role:
    - student
    - son
  backpack:
    dev: dev
  email:  1009083442@qq.com

#Configuration 配置
configuration:
  food:
    name: MilkTea
#    date: 2013-02-02 17:35:44:197
    date: 2018-08-04 20:38:02:223
    productor: Double
    price: 11

#log 配置
#logging:
#  config: classpath:logback-spring.xml

# 静态资源
Spring:
  mvc:
    favicon: true  #修改图标
  # 在 WebMvcAutoConfiguration.java 中 mvcConversionService方設置了時間格式“DateFormat”
  #    default dd/MM/yyyy
  #    date-format:
  messages:     #国际化
    basename: i18n.login
  thymeleaf:
    cache: false


