# properties 配置
person:
  name: Double
  age:  24
  role:
    - student
    - son
  backpack:
    dev: dev
  email:  1009083442@qq.com

#Configuration 配置
configuration:
  food:
    name: MilkTea
#    date: 2013-02-02 17:35:44:197
    date: 2018-08-04 20:38:02:223
    productor: Double
    price: 11

#log 配置
#logging:
#  config: classpath:logback-spring.xml

# 静态资源
spring:
  mvc:
    favicon: true  #修改图标
    #測試jsp 頁面
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp

  # 在 WebMvcAutoConfiguration.java 中 mvcConversionService方設置了時間格式“DateFormat”
  #    default dd/MM/yyyy
  #    date-format:
  messages:     #国际化
    basename: i18n.login
  thymeleaf:
    cache: false
    #測試 jsp 頁面應該關閉 thymeleaf 模板引擎
    #    enabled: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
#    lettuce:
#      pool:
#        #最大连接数
#        max-active: 8
#        #最大阻塞等待时间(负数表示没有限制)
#        max-wait: -1
#        #最大空闲
#        max-idle: 8
#        #最小空闲
#        min-idle: 0
#      shutdown-timeout: 10000
