spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev

server:
#  port: 8082
  servlet:
    context-path: /SpringBoot


logging:
  level:
    com.example.demo: debug
  config: classpath:logback-spring.xml

