spring:
  redis:
    database: 0
    cluster:
      nodes:
        - 127.0.0.1:6380
        - 127.0.0.1:6381
        - 127.0.0.1:6382
        - 127.0.0.1:6384
  #    host: 127.0.0.1
#    port: 6380
#    password:
  #    lettuce:
  #      pool:
  #        #最大连接数
  #        max-active: 8
  #        #最大阻塞等待时间(负数表示没有限制)
  #        max-wait: -1
  #        #最大空闲
  #        max-idle: 8
  #        #最小空闲
  #        min-idle: 0
  #      shutdown-timeout: 10000

